spring:
  datasource:
    url: jdbc:sqlserver://enpalmer.database.windows.net:1433;database=IntelliMemDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: mintuchel
    password: max56685668!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
